### ISSUE TITLE
Comparison with other Laravel HMVC packages 

### ISSUE THREAD

**Issue by Sophist-UK** [hexters/laramodule#2]
I see that this has been created since I last looked for a suitable HMVC package.

How does it compare to alternatives out there?

**Comment by hexters** [comment]
Hi @Sophist-UK thank's for you comment. In this package already supports.
- Support Vite for compailing assets
- Support [InertiaJs](https://inertiajs.com) for Build single-page apps.
- You can make other commands after creating the module, example 
`php artisan module:make Blog --command=custom:command-here`
- You can publish your package for later use or resale at [ppmarket.org](https://ppmarket.org) or others. Publish with command
`php artisan module:publish Blog`
- Already have auth scaffolding for the admin page, which can be seen at [hexters/ldadmin](https://github.com/hexters/ladmin)
- And more 😁😁

Thank you hopefully answered. 😁
